Repository Rafid-009/Hacktober_fest_2020, pull requests merged in 2020-10, with the labels that each got.

#1 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Hacktoberfest-Accepted, good first issue

#2 Hello_World(009 contribute g1)
  Master2Code/Hello_World/C#_code.CS
  Master2Code/Hello_World/C++_code.cpp
  Master2Code/Hello_World/C_code.c
  Master2Code/Hello_World/Dart_code.dat
  Master2Code/Hello_World/Delphi_code.dpr
  Master2Code/Hello_World/Go_code.go
  Master2Code/Hello_World/HTML_code.html
  Master2Code/Hello_World/Java-Script_code.js
  Master2Code/Hello_World/Java_code.java
  Master2Code/Hello_World/Kotlin_code.kt
  Master2Code/Hello_World/Linux_code.txt
  Master2Code/Hello_World/PHP_code.html
  Master2Code/Hello_World/Perl_code.pl
  Master2Code/Hello_World/Python_code.py
  Master2Code/Hello_World/R_code.r
  Master2Code/Hello_World/Ruby_code.ruby
  Master2Code/Hello_World/Rust_code.rs
  Master2Code/Hello_World/Scala_code.scala
  Master2Code/Hello_World/Swift_code.swift
  Master2Code/Hello_World/readme.md
Labels: Hacktoberfest-Accepted, enhancement, good first issue

#5 Create RadixSort.cpp
  Master2Code/RadixSort.py
Labels: Hacktoberfest, Hacktoberfest-Accepted

#9 Create Drchef.cpp
  Master2Code/Hello_World/Drchef.cpp
Labels: Hacktoberfest, Hacktoberfest-Accepted

#12 find duplicates in c
  Master2Code/findduplicates.c
Labels: Hacktoberfest, Hacktoberfest-Accepted

#14 LongestIncreasingSubsequence.cpp
  Master2Code/LongestIncreasingSubsequence.cpp
Labels: Hacktoberfest-Accepted

#19 Binary Search Algorithm
  Master2Code/BinarySearch.cpp
Labels: Hacktoberfest-Accepted

#20 Trie Implementation
  Master2Code/Trie.java
Labels: Hacktoberfest-Accepted

#25 Create Website blocker.py
  Master2Code/Website blocker.py
Labels: Hacktoberfest-Accepted
